/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.json.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JsonUiModule extends AbstractJsonUiModule {

	public JsonUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
