/**
 * generated by Xtext 2.22.0
 */
package pt.bamol.bamolm2.tests;

import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import pt.bamol.bamolm2.Root;

@ExtendWith(InjectionExtension.class)
@InjectWith(BamolM2InjectorProvider.class)
@SuppressWarnings("all")
public class BamolM2ParsingTest {
  @Inject
  private ParseHelper<Root> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Root {");
      _builder.newLine();
      _builder.append("\t ");
      _builder.append("models {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("Models {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("agents {");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("ModelsAgents Provider {");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("attributes {");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("isSystem ");
      _builder.newLine();
      _builder.append("\t\t\t\t\t\t");
      _builder.append("ModelsAgentsAttributes nome  { type String }");
      _builder.newLine();
      _builder.append("\t\t\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Root result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
