/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.vmodel.vmodeldsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pt.bamol.vmodel.vmodeldsl.VModelDslRuntimeModule;
import pt.bamol.vmodel.vmodeldsl.VModelDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class VModelDslIdeSetup extends VModelDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new VModelDslRuntimeModule(), new VModelDslIdeModule()));
	}
	
}
