/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.vmodel.vmodeldsl.ide;


/**
 * Use this class to register ide components.
 */
public class VModelDslIdeModule extends AbstractVModelDslIdeModule {
}
