/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.vmodel.vmodeldsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class VModelDslUiModule extends AbstractVModelDslUiModule {

	public VModelDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
