/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.json.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pt.bamol.json.JsonRuntimeModule;
import pt.bamol.json.JsonStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JsonIdeSetup extends JsonStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JsonRuntimeModule(), new JsonIdeModule()));
	}
	
}
