/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.json.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class JsonProposalProvider extends AbstractJsonProposalProvider {
}
