/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.bamolm2.tests

import pt.bamol.bamolm2.Root
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(BamolM2InjectorProvider)
class BamolM2ParsingTest {
	@Inject
	ParseHelper<Root> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Root {
				 models {
					Models {
						agents {
							ModelsAgents Provider {
								attributes {
									isSystem 
									ModelsAgentsAttributes nome  { type String }
								}
							}
						}
					}
				}
			}
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
