/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.bamolm2.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pt.bamol.bamolm2.BamolM2RuntimeModule;
import pt.bamol.bamolm2.BamolM2StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BamolM2IdeSetup extends BamolM2StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BamolM2RuntimeModule(), new BamolM2IdeModule()));
	}
	
}
