/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.bamolm2;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BamolM2StandaloneSetup extends BamolM2StandaloneSetupGenerated {

	public static void doSetup() {
		new BamolM2StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
