/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.bamolm2;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BamolM2RuntimeModule extends AbstractBamolM2RuntimeModule {
}
