/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.bamolm2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import pt.bamol.bamolm2.ui.highlighting.MySemanticHighlightingConfiguration;
import pt.bamol.bamolm2.ui.highlighting.MySemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BamolM2UiModule extends AbstractBamolM2UiModule {

	public BamolM2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return MySemanticHighlightingCalculator.class;
	}	
	
	public Class<? extends IHighlightingConfiguration> bindILexicalHighlightingConfiguration() {
		return MySemanticHighlightingConfiguration.class;
	}	
}
