/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.vmodel.vmodeldsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class VModelDslStandaloneSetup extends VModelDslStandaloneSetupGenerated {

	public static void doSetup() {
		new VModelDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
