/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.vmodel.vmodeldsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VModelDslRuntimeModule extends AbstractVModelDslRuntimeModule {
}
