/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.json;

import org.eclipse.xtext.conversion.IValueConverterService;

import pt.bamol.json.converter.MyValueConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JsonRuntimeModule extends AbstractJsonRuntimeModule {
	
	@Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
    	// return null
        return MyValueConverter.class;
    }    
}
