/*
 * generated by Xtext 2.22.0
 */
package pt.bamol.json;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JsonStandaloneSetup extends JsonStandaloneSetupGenerated {

	public static void doSetup() {
		new JsonStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
